paginate:  5
permalink: /posts/:title/
url:       http://zofe.com.br
markdown:  Kramdown
excerpt_separator: someNonsenseString

title: "Zone Of Front-Enders - ZOFE"
exclude: [
  'episodios',
  'README.md',
  'package.json',
  'Gruntfile.js',
  'node_modules',
  'Gemfile*',
  'assets/sass'
]
cover-image: "//i.imgur.com/3wwFY7n.png"

members:
  - name: Almir Filho
    url: https://twitter.com/almirfilho
    image: http://www.gravatar.com/avatar/92c3db0f88b5ea3722addf91a1ab11cd?s=300
  - name: Bruno Passos
    url: https://twitter.com/brunopassos
    image: http://gravatar.com/avatar/0905f523f153bdfbca51d2dfb7c2dd27?s=300
  - name: Caio Gondim
    url: https://twitter.com/caio_gondim
    image: http://www.gravatar.com/avatar/212b8b6589f7e98dae14e6517101f427?s=300
  - name: Daniel Filho
    url: https://twitter.com/danielfilho
    image: http://www.gravatar.com/avatar/3f2ebf61315d43cae59e727dab091620?s=300
  - name: Rafael Rinaldi
    url: https://twitter.com/rafaelrinaldi
    image: http://www.gravatar.com/avatar/ffc5102ee85d0d7ec57200fa3e6b1fce?s=300
