plugins:           ["jekyll-paginate", "jekyll-lunr-js-search"]
paginate:          5
paginate_path:     "/posts/page:num/"
permalink:         "/posts/:title/"
url:               "https://zofe.com.br"
markdown:          "Kramdown"
excerpt_separator: <!-- excerpt -->
encoding: UTF-8
# excerpt_separator: someNonsenseString

title: "Zone Of Front-Enders - ZOFE"
exclude: [
  'episodios',
  'README.md',
  'package.json',
  'Gruntfile.js',
  'node_modules',
  'Gemfile*',
  'assets/sass'
]

lunr_search:
  js_dir: "assets/js"

cover-image: "//i.imgur.com/3wwFY7n.png"

members:
  - name: Daniel Filho
    url: https://twitter.com/danielfilho
    image: https://www.gravatar.com/avatar/3f2ebf61315d43cae59e727dab091620?s=300
  - name: Isa Silveira
    url: https://twitter.com/silveira_bells
    image: https://www.gravatar.com/avatar/91b0fc08849c4128f1eed542c057fd27?s=300
